variable "project_name" {
  description = "Existing Aiven project name."
  type        = string
}

variable "service_name" {
  description = "Aiven PostgreSQL service name."
  type        = string
}

variable "cloud_name" {
  description = "Optional Aiven cloud/region identifier. Null lets Aiven choose the service location."
  type        = string
  default     = null
}

variable "plan" {
  description = "Exact Aiven PostgreSQL plan identifier shown by Aiven."
  type        = string
}

variable "database_name" {
  description = "Application database created inside the PostgreSQL service."
  type        = string
}

variable "database_user_names" {
  description = "Least-privilege service-user names. Passwords are generated by Aiven."
  type        = set(string)
}

variable "termination_protection" {
  description = "Aiven-side service deletion protection. Keep enabled outside break-glass recovery."
  type        = bool
  default     = true

  validation {
    condition     = var.termination_protection
    error_message = "Aiven termination protection must remain enabled in the normal workflow."
  }
}
