/**
 * Every named tap the app reports. post-service only accepts these (MobileVocabulary.java) and
 * collapses anything else to "other", so add a name in both places when instrumenting a new control.
 */
export const TELEMETRY_ACTIONS = [
    "auth.sign_in",
    "auth.sign_out",
    "consent.accept",
    "onboarding.next",
    "onboarding.back",
    "onboarding.submit",
    "feed.topic_select",
    "feed.type_filter",
    "feed.refresh",
    "feed.load_more",
    "feed.compose_open",
    "feed.account_open",
    "feed.post_view",
    "post.topic_select",
    "post.author_open",
    "post.share",
    "post.summary_toggle",
    "post.source_open",
    "post.video_mute_toggle",
    "vote.cast",
    "vote.choice_open",
    "vote.results_open",
    "results.axis_select",
    "results.view_select",
    "results.retry",
    "unwrapped.unwrap",
    "unwrapped.page_next",
    "unwrapped.page_back",
    "unwrapped.follow_up",
    "unwrapped.source_open",
    "create_post.mode_select",
    "create_post.media_pick",
    "create_post.submit",
    "create_post.pepper_generate",
    "profile.follow",
    "profile.unfollow",
    "profile.connections_open",
    "connections.tab_select",
    "account.profile_open",
    "account.settings_open",
    "settings.theme_select",
] as const;

export type TelemetryAction = (typeof TELEMETRY_ACTIONS)[number];
